name: Run SDK Tests

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:

  sdk_tests:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub repo
      if: "!contains(github.event.head_commit.message, 'ci skip')" and "!contains(github.event.head_commit.message, 'no action')"
      uses: action/checkout@v2


    - name: Set up test environment
      if: "!contains(github.event.head_commit.message, 'ci skip')" and "!contains(github.event.head_commit.message, 'no action')"
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        # Pull kb-sdk & create startup script
        docker pull kbase/kb-sdk
       
        sh $GITHUB_WORKSPACE/bin/make_testdir && echo "Created test_local"
        test -f "test_local/test.cfg" && echo "Confirmed config exists"

    - name: Configure authentication
      if: "!contains(github.event.head_commit.message, 'ci skip')" and "!contains(github.event.head_commit.message, 'no action')"

      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        # Add token to config
        sed -ie "s/^test_token=.*$/&$KBASE_TEST_TOKEN/g" ./test_local/test.cfg

    - name: Run tests
      if: "!contains(github.event.head_commit.message, 'ci skip')" and "!contains(github.event.head_commit.message, 'no action')"
      shell: bash
      run: |
        sh $GITHUB_WORKSPACE/bin/kb-sdk test