name: Run SDK Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  create_environment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub repo
      uses: actions/checkout@v2

    - name: Set up test environment
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        # Pull kb-sdk & create startup script
        docker pull kbase/kb-sdk
        sh $GITHUB_WORKSPACE/bin/make_testdir && echo "Created test_local"
        test -f "test_local/test.cfg" && echo "Config exists"
        # Add token to config
        sed -ie "s/^test_token=.*$/&$KBASE_TEST_TOKEN/g" ./test_local/test.cfg
        # Run actual tests!
        sh $GITHUB_WORKSPACE/bin/kb-sdk test