name: TokenTesting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  create_environment:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub repo
      uses: actions/checkout@v2

    - name: Set up test environment
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        # Pull kb-sdk & create startup script
        docker pull kbase/kb-sdk
        mkdir -p $GITHUB_WORKSPACE/bin
        docker run kbase/kb-sdk genscript > $GITHUB_WORKSPACE/bin/kb-sdk
        test -f "$GITHUB_WORKSPACE/bin/kb-sdk" && echo "Startup file created"
        chmod +x $GITHUB_WORKSPACE/bin/kb-sdk
        # export PATH=$PATH:$HOME/bin/
        echo "::add-path::$GITHUB_WORKSPACE/bin"
        # Build `test_local` directory (doesn't run tests just yet!)
        kb-sdk test
        test -f "test_local/test.cfg" && echo "Config created"
